### ISSUE TITLE
PR-A 中测试代码需要的没有所需文件

### ISSUE THREAD

**Issue by oceanogeology** [LSPRC/PRCV2020-LSPRC#1]
attr_gt_filename = "data/Attr_testdata_info.txt"
    query_filename = "data/attr_query_index.txt"
    query_res_filename = "../../outputs/query_res_DL_zhike.csv"
请上传这些文件或者说明下文件里面的内容是什么？

**Comment by LSPRC** [comment]
> ```
> attr_gt_filename = "data/Attr_testdata_info.txt"
> query_filename = "data/attr_query_index.txt"
> query_res_filename = "../../outputs/query_res_DL_zhike.csv"
> ```
> 
> 请上传这些文件或者说明下文件里面的内容是什么？

Attr_testdata_info.txt 为ground truth，不会提供给大家；attr_query_index.txt 为需要检索的属性组合，可以在下载的数据中找到，具体说明请查看下载的数据中README文件；query_res_DL_zhike.csv为提交的检索结果，具体输出格式和注意事项也请阅读README文件。如果还有其他问题可邮件或微信联系，谢谢！
